#!/bin/bash

BASE=~/.dotfiles

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf $BASE/config/vimrc ~/.vimrc
vim +PlugInstall +qall

# nvim
mkdir -p ~/.config/nvim/autoload
ln -sf $BASE/config/vimrc ~/.config/nvim/init.vim
ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/
nvim +PlugInstall +qall
