#!/bin/bash

info() {
  printf "$(tput setaf 5)⁙ %s$(tput sgr0)\n" "$@"
}

success() {
  printf "$(tput setaf 64)✓ %s$(tput sgr0)\n" "$@"
}

type_exists() {
  if type $1 > /dev/null 2>&1; then
    return 0
  fi
  return 1
}
