# espanso configuration file
# https://espanso.org/docs/

matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ",br"
    replace: "Best,\nFred Oliveira"

  - trigger: ",sig"
    replace: "Fred Oliveira\nhttps://helloform.com\nhttps://twitter.com/f"

  - trigger: ",csig"
    replace: "Fred Oliveira\nVP of Engineering, Capital Factory\nhttps://capitalfactory.com\nhttps://twitter.com/f"
